# Changes here will be overwritten by Copier
AnswerStrategy: minimum
Authors: Misha Mikhasenko <mikhail.mikhasenko@gmail.com>
Indentation: 4
JuliaMinVersion: '1.6'
License: MIT
LicenseCopyrightHolders: Misha Mikhasenko
PackageName: TriangleSingularity
PackageOwner: mmikhasenko
PackageUUID: 806edd40-9488-453b-b3e3-cb1e12902d3c
_commit: v0.10.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
